"""add_documents_table

Revision ID: 1c57b001aa85
Revises: 
Create Date: 2026-04-24 19:13:43.789582

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '1c57b001aa85'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    op.create_table(
        'documents',
        sa.Column(
            'id',
            sa.UUID(),
            server_default=sa.text('gen_random_uuid()'),
            nullable=False,
        ),
        sa.Column('filename', sa.String(length=512), nullable=False),
        sa.Column('file_type', sa.String(length=32), nullable=False),
        sa.Column('size_bytes', sa.BigInteger(), nullable=False),
        sa.Column(
            'status',
            sa.String(length=32),
            server_default=sa.text("'UPLOADED'"),
            nullable=False,
        ),
        sa.Column('content_hash', sa.String(length=64), nullable=False),
        sa.Column(
            'chunk_count',
            sa.Integer(),
            server_default=sa.text('0'),
            nullable=False,
        ),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
